<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>AppiumAdvanced</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PercyIO.Appium" Version="3.0.8"/>
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0"/>
    <PackageReference Include="Appium.WebDriver" Version="4.4.5"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.6" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
